# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: titanium

builds:
  # Build for macOS AMD64
  - id: darwin_amd64
    main: cmd/titanium/main.go
    goos:
      - darwin
    goarch:
      - amd64
    binary: ti
    env:
      - CGO_ENABLED=1

  # Build for macOS ARM (Apple Silicon)
  - id: darwin_arm64
    main: cmd/titanium/main.go
    goos:
      - darwin
    goarch:
      - arm64
    binary: ti
    env:
      - CGO_ENABLED=1

  # Build for Linux AMD64
  - id: linux_amd64
    main: cmd/titanium/main.go
    goos:
      - linux
    goarch:
      - amd64
    binary: ti
    env:
      - CGO_ENABLED=0

  # Build for Linux ARM64
  - id: linux_arm64
    main: cmd/titanium/main.go
    goos:
      - linux
    goarch:
      - arm64
    binary: ti
    env:
      - CGO_ENABLED=0

  # Build for Windows AMD64
  - id: windows_amd64
    main: cmd/titanium/main.go
    goos:
      - windows
    goarch:
      - amd64
    binary: ti.exe
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

docker:
  - image_templates:
      - "rianfowler/project-orca:{{ .Version }}"
      - "rianfowler/project-orca:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--platform=linux/arm64"
    extra_files:
      - LICENSE
      - README.md

dockerhub:
  - username: "rianfowler"
    secret_name: DOCKERHUB_PAT
    images:
      - rianfowler/project-orca
    description: "Project Orca - A powerful CLI tool"
    full_description:
      from_file: DOCKER.md
