package main

import (
	"embed"
	"io/fs"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	_ "github.com/titan-syndicate/titanium/docs" // docs is generated by Swag CLI
)

//go:embed swagger-ui/*
var swaggerUI embed.FS

// @title           Titanium Project Service
// @version         0.1.0
// @description     API for managing projects in the Titanium platform
// @host            localhost:8080
// @BasePath        /
func main() {
	e := echo.New()

	// Middleware
	e.Use(middleware.Logger())
	e.Use(middleware.Recover())

	// Serve Swagger UI
	swaggerFS, err := fs.Sub(swaggerUI, "swagger-ui")
	if err != nil {
		e.Logger.Fatal(err)
	}
	e.GET("/swagger/*", echo.WrapHandler(http.StripPrefix("/swagger/", http.FileServer(http.FS(swaggerFS)))))

	// Serve OpenAPI spec
	e.GET("/api/spec/project.yaml", func(c echo.Context) error {
		return c.File("api/spec/project.yaml")
	})

	// Start server
	e.Logger.Fatal(e.Start(":8080"))
}
