name: Promote Prerelease

on:
  release:
    types: [created]

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0

      - name: Run GoReleaser
        id: goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Tell GoReleaser to create a non-prerelease
          SKIP_PRERELEASE: true

      - name: Create workflow summary
        if: success()
        run: |
          echo "## Release Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Version Information" >> $GITHUB_STEP_SUMMARY
          echo "- Version: ${{ github.event.release.tag_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Build Artifacts" >> $GITHUB_STEP_SUMMARY
          echo "The following artifacts were created:" >> $GITHUB_STEP_SUMMARY
          echo "- Binary archives for multiple platforms" >> $GITHUB_STEP_SUMMARY
          echo "- Checksums for all artifacts" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Release Notes" >> $GITHUB_STEP_SUMMARY
          echo "Release notes and download links are available in the [GitHub Release](https://github.com/titan-syndicate/titanium/releases/tag/${{ github.event.release.tag_name }})" >> $GITHUB_STEP_SUMMARY