name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: rianfowler
          password: ${{ secrets.DOCKER_PAT }}

      # Decode and install your deploy key into ssh-agent
      - name: Configure SSH for Homebrew Tap
        env:
          DEPLOY_KEY_B64: ${{ secrets.BREW_DEPLOY_KEY }}
        run: |
          # prepare ssh dir
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # decode the key and add it
          echo "$DEPLOY_KEY_B64" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # start the agent & add the key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

          # trust GitHub’s host key (so checkout won’t prompt)
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
          distribution: goreleaser-pro
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_PRO_KEY }}
          # Ensure we create a full release, not a prerelease
          GORELEASER_CURRENT_TAG: ${{ github.ref_name }}
          GORELEASER_PREVIOUS_TAG: ${{ github.ref_name }}

      - name: Create workflow summary
        if: success()
        run: |
          echo "## Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Version: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- Release: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- Docker Image: rianfowler/project-orca:${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY