name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: rianfowler
          password: ${{ secrets.DOCKER_PAT }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
          distribution: goreleaser-pro
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_TITANIUM_PUBLISH_GHPAT }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_PRO_KEY }}
          # Ensure we create a full release, not a prerelease
          GORELEASER_CURRENT_TAG: ${{ github.ref_name }}
          GORELEASER_PREVIOUS_TAG: ${{ github.ref_name }}

      - name: Create workflow summary
        if: success()
        run: |
          echo "## Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Version: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- Release: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- Docker Image: rianfowler/project-orca:${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY